const userActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  REGISTER_START: 'REGISTER_START',
  SIGN_IN_SET_LOADING: 'SIGN_IN_SET_LOADING',
  SIGN_IN_SET_ERROR: 'SIGN_IN_SET_ERROR',
  SIGN_IN_SET_USER: 'SIGN_IN_SET_USER',
}

export default userActionTypes;